### ISSUE TITLE
Decide on backend framework

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#1]
Leave any comments on backend frameworks and approaches here.

**Comment by hexjelly** [comment]
8balle mentioned that Feathers framework, not used or have any opinions on anything here (except pls no Meteor 8). Feathers looked like could be ok though, at least putting as a suggestion for choices anyway.

**Comment by demiters** [comment]
I'm using Feathers in a client project right now so can confirm it's very useful once you learn the approaches it takes. At first it's just a thin layer over Express and then you can keep plugging in additional Feathers feature packages, it's very modular - you just take what you actually need to use. At the core there's what it calls services - https://docs.feathersjs.com/services/readme.html

Anyway, getting started with it isn't any more difficult than with Express and you get benefits at every layer of the app. Just my 2 cents.
