### ISSUE TITLE
Find the best material design react component

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#10]

**Comment by foxtrada** [comment]
Has anyone thought more about this? I made some quick sketching with mdl (can see something in here: http://janka.la/eol-horror/ )  and I don't really like the looks. Maybe a bit too much whitespace and not many components seem useful our intentions, looks more useful to some more app-like things.  Could we maybe use some css grid and resets only and decide more on the design principles ourselves? Or are there more advantages using the React Material UI for example? Surely some custom components and stuff but are they really useful? Looks like the most important thing for us are tables.

**Comment by hexjelly** [comment]
Didn't try anything out yet, but agree that it seems like maybe not best fit without having to change a lot, and then might as well make some own thing on top of barebones grid system (~lol~ how about flexbox pls..)

[http://bulma.io](http://bulma.io) looks interesting maybe? Probably million others too for that matter if we are looking at alternatives

**Comment by demiters** [comment]
I'm using [react-mdl](https://github.com/react-mdl/react-mdl) and I like it a lot. Can pick from many different color schemes. Also [react-mdl-extra](https://github.com/HriBB/react-mdl-extra) for some additional dropdown based components. So with these 2 can make pretty much anything needed in frontend so unless going for some entirely different visual style they might work well enough without much overriding of base styles.

**Comment by foxtrada** [comment]
That react-mdl has a deprecation notice and advises to use [material-components-web](https://github.com/material-components/material-components-web), as far as I understood this doesn't have the table component implemented at all yet (looked at it yesterday). Anyways I am most "worried" about the overall looks, for example the headings, tables and lists having large margins. These can be ofc overridden but I don't know if it might cause unexpected problems/ugliness when combining components on the layouts? So unless these material components give some real advantage it might be easier to go with some css frameworks that require mostly just picking the colors.

**Comment by ville-j** [comment]
I believe we are settled with using [https://material-ui.com](https://material-ui.com) for now.
