### ISSUE TITLE
Existing rules for hiding times

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#107]
There's a number of rules in place we need to follow to hide times. For example hiding WR's not yet published on official WR table.

- If SiteLock is 1 hide times for level on eol site (don't think this hasn't been used for years, we can probably just ignore this)
- If Hidden is 1 use weeklybest table instead of besttime, and hide times from allfinished with higher TimeIndex than the one stored in corresponding Weekly field in levelpack table
- If TimeIndex exists in weeklywrs don't show the time
- If Locked is 1 don't show times in level (effectively consider the level to not exist)

I'm very open to contesting some of these things, so let's have a discussion. Mostly this is about internals, should we keep with updating them once a week etc.

**Comment by ville-j** [comment]
Has anyone had any opinion about this or should we just implement it the way it is now? Would be nice to get to show other than battle times already.

**Comment by sunehs** [comment]
Not really. We can just go with this for now. No matter what we'll have to keep at least some of it in the longterm as well.

**Comment by ville-j** [comment]
I implemented filtering for best times query in my commit 001e29dff9ef56f46b56282cfb47ab4054ae29ff, it's hard to test though.

**Comment by sunehs** [comment]
I did some testing, seems to work as it should.
