### ISSUE TITLE
Improvements to the replay page

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#112]
- [x] Link to level
- [x] Highlight current replay in list of other replays in level

Optional
- [x] Comments section
- [x] Ratings

**Comment by pawq** [comment]
I'll implement the first two. Comments and ratings need further discussion I guess, but I wouldn't be able to implement those anyway.

**Comment by sunehs** [comment]
Comments and ratings would require authentification to be made first.

Comments should be pretty straight forward, just a list of comments.

For ratings we should decide how we want to rate. Might be a good idea to go with X/10 though, to go in line with the !lev and !rec rating in in-game chat.

**Comment by pawq** [comment]
Agree with all of the above. Would be great if we could also back-track !rec and !lev ratings from in-game chat and add them to the levels and battle replays when it's been implemented.
