### ISSUE TITLE
Consider merging replay and level pages

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#113]
Once we add the list of best times to the replay page, most features would be duplicated between the two. At this point I think it's worth asking if it's worth combining them, even if it might require quite a bit of extra work, because otherwise jumping back and forth may be a bit impractical.

There are potential conflicts with comments, ratings and things like that, but I think it should be possible to neatly separate them in components on the joint page.

In terms of navigation, url could perhaps be along the lines of `https://test.elma.online/levels/LevelIndex/UUID`?

In terms of layout, could perhaps reserve the right bar for replay stuff (replay info on top, then maybe ratings & comments, then list of other replays), and the left side for level stuff (recplayer on top, showing either static lev or fastest finished replay by default, then level info, then table with times, and perhaps ratings & comments somewhere too).

Just a loose idea of course, but better consider now than when the site is finished imo. I can't help but notice this every time I go from level page to replay page and back, that they're already very similar, and would get almost identical once we start showing best replays on the level page or showing times on the replay page.

**Comment by ville-j** [comment]
I thought about this (about two years ago so can't remember exactly what were the reasons) and came to a conclusion that it's a bad idea. At least it would make replay urls longer and in the end they are different things and you should be able to link to each separately. There is a lot of additional data you might want to show about level and squeezing all that information on the replay page might get tricky. And what is combining them trying to achieve anyways? If they are showing some of the same data the same component can be used in both pages and is not much more work.
