### ISSUE TITLE
Level pack pages

### ISSUE THREAD

**Issue by ville-j** [elmadev/elmaonline-site#123]
List of level packs (reference [https://elmaonline.net/statistics](https://elmaonline.net/statistics)) and single level pack page (reference [https://elmaonline.net/statistics/levelpack/ALP](https://elmaonline.net/statistics/levelpack/ALP).

**Comment by pawq** [comment]
👍 

There are a loooooot of things that need to be reworked from the old system though 😉 Are you planning to get started on it soon? Could try to write up some spec tonight.

**Comment by ville-j** [comment]
I was going to start just now.. basically one page to list all the level packs and other page for listing the levels of a selected level pack. Those should be doable right or what did you have in mind?

**Comment by pawq** [comment]
One crucial thing is to add a "Designer" field, as lots of packs are uploaded by other people. That's presumably a db thing too, so not sure if you can do that, but yeah. Ofc I realise that the packs uploaded to-date don't have this field, but most should be possible to back-track (and I think this is quite important, I'd be quite happy to do it personally). Uploaded date would be nice too, but no idea if it's kept in the db, not crucial anyway. That's it for the list of packs I guess.

As for individual level packs, it's extremely important to display filename for every lev, and make it possible to go to an individual level page. Atm clicking on a lev only shows its best times within the levpack, and it's literally not possible to check the filename. Not sure how it's best to lay this out. Perhaps, in the list of levs, it could be displayed as "x. *filename* (*levname*)" with a link to best times, and then have a "Go to level page" link on the best times page? Would be nice to have a full list of links to levs on the main levpack page tho, often want to middle-click multiple levs to look at later.

**Comment by pawq** [comment]
Anyway, I suppose once the skeleton is there, it should be fairly easy to modify layout as needed, so don't worry too much now. I'd be happy to contribute too when I'm back 🙂 Good luck!

**Comment by ville-j** [comment]
Good points! Designer and upload date are not available atm as far as I know but otherwise sounds doable. I had an idea about the first version layout so gotta try that, and of course it's not that hard to change later or add more info.
