### ISSUE TITLE
Swap out Redux for something better?

### ISSUE THREAD

**Issue by demiters** [elmadev/elmaonline-site#128]
Before we dive neck deep into a sea of Redux boilerplate files we could consider swapping it out for a more modern hook based approach to state management like https://github.com/ctrlplusb/easy-peasy which looks just as if not more powerful while easier to write and maintain.

There's a ton of articles like this too https://staleclosures.dev/from-redux-to-hooks-case-study/ so it's a good moment to react (hehe) to the landscape changing while we're not invested much in Redux yet.

**Comment by sunehs** [comment]
I haven't tried using hooks at all yet, so hard for me to really judge what would fit the project best.

As far as redux goes, I've only somewhat recently really started to understand and appreciate it. I wouldn't mind sticking to that, but also not against something else. With something like reduxsauce you can limit the amount of boilerplate code quite a bit. And I like using something that's mature and popular.

Hooks being part of react itself I don't doubt it'll stick around and become popular, but picking some package to use on top of it may be difficult as it's all really new currently. I agree with the sentiment though that it would be wise to pick now if we want to do something other than redux. And would much prefer the simplest solution, so it's easier for js/react rookies to jump in (already a lot of things to understand).

**Comment by ville-j** [comment]
It's unnecessary to jump on to every new hype and trend, redux works very well for this project and in general. That being said I'm not much invested in redux, I use mostly mobx myself.

**Comment by demiters** [comment]
I understand that, though my argument is that hooks do look like they're here to stay and getting widely adopted, with Redux being dropped left and right for being too burdensome for many applications. It used to be the only mature choice, not so much anymore. I don't mind sticking to it with some boilerplate abstraction as Kopaka mentioned, but I think options like Easy Peasy are (surprise!) easier for newcomers to wrap their heads around. Besides, there's this sentiment:
![image](https://user-images.githubusercontent.com/7239988/56561027-af396580-65ae-11e9-9b45-d24b77647af1.png)

**Comment by ville-j** [comment]
Do you understand what that Easy Peasy is and what it does? It seems to be using redux under the hood which makes your arguments sound a bit weird.

**Comment by demiters** [comment]
I guess I was arguing against vanilla Redux then :man_shrugging:

**Comment by sunehs** [comment]
Something to consider https://github.com/reduxjs/react-redux/releases/tag/v7.1.0-alpha.1
