### ISSUE TITLE
Powering up our forms

### ISSUE THREAD

**Issue by demiters** [elmadev/elmaonline-site#129]
We don't have any forms yet really but I'm about to add a few for auth.

To make form state management, validation etc easier there are useful packages to put under the hood for our form components, like
https://github.com/kevinwolfcr/formal/tree/master/packages/formal-web and https://github.com/final-form/final-form of which the latter seems more powerful but not sure we'd need that power. The former is more lightweight and uses hooks which is cool ofc.

Maybe someone has a different preference?

**Comment by sunehs** [comment]
Don't really have any experience with any such, so no real prefence. But would say the simpler the better so people don't have to learn something complicated.

**Comment by sunehs** [comment]
formal-web has been settled on for now
