### ISSUE TITLE
Jest tests removed

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#130]
I removed the jest tests requirement since it was failing and I don't know anything.

https://github.com/elmadev/elmaonline-site/commit/cecc6592c4c5b89d80b573ac3aed31466b250bcf

Unit tests is not something I've ever done, so I don't know if it's something we should even bother with. Anyway just putting this issue up so people know why it was removed. I've no idea how to fix it, so didn't really want to spend time learning it for the sake of one test.

**Comment by demiters** [comment]
Yeah not required for now. I've done unit and snapshot tests but see no real value from them. Someone else can do them if they want. E2E tests with Cypress is something I wanna do later on though and those are the most useful imo.

**Comment by ville-j** [comment]
You can update the snapshots just by running `jest --updateSnapshot` and then the tests should pass. But those are quite useless at this stage.
