### ISSUE TITLE
News

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#151]
News section has gone pretty unused over the last years. Not sure what should be the goal of it? Just about site/game features, or also for general things happening in the community.

Can/should it be more integrated with other things, such as eol facebook, discord, lauta.

**Comment by demiters** [comment]
I would suggest using Notifications tab on Settings page for this, and renaming Settings to Account, with mail icon next to it, with Badge component that can be used to draw attention to new items.

**Comment by sunehs** [comment]
So you mean show the news items on that page? Either way I don't care much about where they are, most important is some good notification system so people notice them.

**Comment by sunehs** [comment]
made a quick component to show last five news items so we can finish the milestone, for more advanced stuff and notifications I've made #353
