### ISSUE TITLE
Attach chat logs from the duration of the battle to the battle results page

### ISSUE THREAD

**Issue by demiters** [elmadev/elmaonline-site#17]
The idea comes from watching Twitch vods where it's often interesting to read what people were talking about when the stream took place. I'm also often curious what were people's reactions about some battle. This could include like 2 minutes before and after the battle too.

**Comment by ville-j** [comment]
The first version of this feature is now implemented on dev branch. However it is quite slow so maybe it's not possible to put it live just yet. The least that could be done is to add an index to the chat table timestamp column.

**Comment by sunehs** [comment]
I added an index on Entered in the test db, it speeds it up a lot. We can also consider removing the ordering in the sql query and order it in the frontend. Before adding the new index it used index on the ordering but not it uses index on the between clause and not the ordering.
