### ISSUE TITLE
Update the status of the project

### ISSUE THREAD

**Issue by ville-j** [elmadev/elmaonline-site#25]
Can you update and add information about the status of this project? What's the deal with the different branches and are any of them up-to-date and relevant? Is the boilerplate that's going to be used already fixed (both frontend and backend)? Are the frontend and backend going to get different repositories (and when)?

**Comment by sunehs** [comment]
I updated the readme to reflect current status. None of current code/branches are relevant. Backend and frontend seem very integrated with each other in many starter kits, so not sure if it's practical to split them.

**Comment by Ben3eeE** [comment]
Since contributions are accepted and the current status is in the readme I am going to close this issue.
