### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#28]
- [x] Login
- [x] Register
- [x] Token system thing between backend/frontend

**Comment by demiters** [comment]
Just FYI I've settled on using https://github.com/simov/grant for this as Passport looks unmaintained.

**Comment by ville-j** [comment]
Is there some problem with this as it has been "in progress" for over a year already?

**Comment by sunehs** [comment]
@demiters any progress? this would be nice to get done soon as many other features depend on it

**Comment by demiters** [comment]
Sorry about the holdup, I think I have some time this weekend to move this along.
