### ISSUE TITLE
Connect Discord account to site account

### ISSUE THREAD

**Issue by demiters** [elmadev/elmaonline-site#294]
Will add `passport` and `passport-discord` dependencies unless there's a good argument for rolling our own.

**Comment by sunehs** [comment]
Is passport still the best option? You did some grant code last year https://github.com/elmadev/elmaonline-site/commit/7d4e6ac47d291c781849dc0c9ba1511848dbe023#diff-23821ae067a9c7dfb6227774aefb39fa3951a5874ea953b9401dfc80175c026c

Not that I have any preference.

**Comment by demiters** [comment]
Will check again and see what's better, thanks for reminder.

**Comment by sunehs** [comment]
For reference
https://disco-oauth.vercel.app/
https://discord.com/developers/docs/topics/oauth2
