### ISSUE TITLE
Levpack Personal tab erroneous time display

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#368]
Atm the Personal tab in level pack pages displays the same times as the Records tab, i.e. WRs.

Example:
https://elma.online/levels/packs/2p
But it seems to be the case in all levpacks.

Presumably it should display the PRs of the kuski that's logged in, and I think ideally the Personal tab should be hidden / not displayed if the user is not logged in.

**Comment by pawq** [comment]
[00:47] Markku: you were able to replace the kuski name in personal tab and that way look at anyone's prs for that pack, that's very useful so i don't think it should be hidden in any case

**Comment by sunehs** [comment]
Fixed in https://github.com/elmadev/elmaonline-web/pull/11
