### ISSUE TITLE
Profile icon hidden in smaller screens

### ISSUE THREAD

**Issue by metsavir** [elmadev/elmaonline-site#374]
User can't log in/out or navigate to settings in smaller screens because search area is too wide (and top bar is not scrollable).

<img width="330" alt="Screenshot 2021-02-08 at 22 47 52" src="https://user-images.githubusercontent.com/5804674/107279517-d00ecb80-6a5f-11eb-9e62-afc90185f964.png">

**Comment by j-masci** [comment]
perhaps this can be done by adding a new search form on this page here: https://elma.online/search

then in the header, just have a search icon which links to the page, and a profile/login icon/text.
