### ISSUE TITLE
Optional upload of 2nd-last place recs for battles

### ISSUE THREAD

**Issue by j-masci** [elmadev/elmaonline-site#376]
I think it would be cool to give people the option to manually upload a rec to a battle. The rec wouldn't show up anywhere except in the battle so people could spam upload them if they prefer and shouldn't have any negative effect on users of the site. 

The idea would be that you can upload it if you feel its interesting, whether its very close 2nd place, or a different style or whatever. The first place rec would still show by itself when someone views the battle. But you can merge in additional recs to compare styles.

Would probably then want to add a column for number of replays to the battles list, so people know more were uploaded.

I would say not high priority but interesting feature perhaps.

**Comment by ville-j** [comment]
I think the current upload should be enough, battle page could display other replays uploaded for the level. I think it's already a bit problematic that battle winning replays are different from other uploaded replays, you can't link directly to them, can't comment/rate them etc... this should be somehow fixed and the rest is just up to making the ui more sensible.

**Comment by ddawned** [comment]
Could add the possibility to link the replay to a battle when uploading a rec, and a check during upload if it was driven during the battle or not. (So that afterbattle/not-the-best-result recs also showed on the battle page).

**Comment by ville-j** [comment]
As far as i know it's not possible to know when a replay was driven. You could compare the time of the replay and see if the player drove that time during a battle and then assume it was that run. That can be done alreadu now, without adding any complexity or user action to rec upload.

**Comment by j-masci** [comment]
Perhaps just show other replays from level on battle page if they exist.  This would achieve more or less the same thing.

**Comment by j-masci** [comment]
Sorry that was already said.
