### ISSUE TITLE
Show level pack adminship

### ISSUE THREAD

**Issue by humisevaharju** [elmadev/elmaonline-site#382]
Pretty minor and specific issue, but a situation emerged which showed that this could be useful. 

Tej noticed an incorrect version of a level in a pack, and wanted to inform the administrator(/uploader) of the the pack of it so that person could fix the issue. However, that information is not available on the new site as it was in the old. There just needs to be clear indication that the administrator/uploader of the pack is not necessarily the maker/owner of the levels.

In case at some points mods are getting level pack administering rights (a thing that has been talked about at some point, dunno if anything is happening towards that yet) there could be some sort of easy ticket system that allows the user to notify both the moderators and the level pack admin of whatever issue they have.

**Comment by pawq** [comment]
Definitely agree with this. Mentioned it some time ago already, but forgot to add an issue. I think mods should have admin rights for packs by default, and the owner of the pack should be displayed too. A ticket system would be ideal ofc :-)
