### ISSUE TITLE
Can't zoom rec/map viewer on mobile. 

### ISSUE THREAD

**Issue by j-masci** [elmadev/elmaonline-site#387]
Default zoom should be zoomed out for mobile I think. 

Add clickable zoom controls if doable.

Thoughts?

**Comment by pawq** [comment]
Agree 100%. Viewing levels is basically impossible on mobile because can't zoom at all so can only see a tiny part of the lev. I vaguely remember someone saying that pinching is not possible to implement, if that's true then at least some zoom controls would be great.

**Comment by j-masci** [comment]
Submitted PR to lessen default zoom on mobile which should at least help. Still would like to add controls in the future.
