### ISSUE TITLE
Two repos or one?

### ISSUE THREAD

**Issue by demiters** [elmadev/elmaonline-site#4]
Pretty common to see backend isolated from frontend nowadays. Some good arguments here https://quickleft.com/blog/six-reasons-we-split-front-end-and-back-end-code-into-two-git-repositories-working-with-github-repositories/

**Comment by sunehs** [comment]
Good points, one issue would be users having no idea which to post in when reporting bugs/suggestions, can't even get them to post on the correct lauta thread relating game or site. On the other hand most stuff people report might be frontend related and most will probably use irc/lauta anyway.

**Comment by hexjelly** [comment]
I don't know how many norm users are going to register to GH and also post issues here anyway, probably not a big problem. People are going to say something in IRC or Discord more than likely like said and leave it at that. We can just add it ourselves here where it's most appropriate if splitting up codebase.

I don't have any particular opinion either way, I'm sure both have their pros and cons, but splitting could be logically ok. If some people are feeling like making some design, CSS or general UI parts but maybe are afraid to fuck with something, they could be free to concentrate on frontend and looks only while still joining or something.

**Comment by sunehs** [comment]
Back and frontend is very intertwined in the starter kit we're using now, so this may not be practical, unless someone wants to give splitting it up a try.
