### ISSUE TITLE
Kuski page: Show players by country and sorted by ranking.

### ISSUE THREAD

**Issue by j-masci** [elmadev/elmaonline-site#411]
And sort countries by cumulative rating.

Is this possible with the current rating system?

Obv, could have a separate tab for this and additionally keep the existing alphabetical system in place.

**Comment by sunehs** [comment]
I wonder if anyone even uses it in current state, personally I never have a reason to browse that page, only search for a specific kuski

could be made as some filter/order options maybe, then that page could become a bit more useful

> 
> 
> And sort countries by cumulative rating.

should be, but not sure this really makes sense with an ELO ranking

**Comment by j-masci** [comment]
True perhaps sort by number of players makes sense. Just something to show more significant countries near top.

**Comment by j-masci** [comment]
Implemented
