### ISSUE TITLE
Show recent replay comments on home page?

### ISSUE THREAD

**Issue by j-masci** [elmadev/elmaonline-site#412]
Could omit comments by the uploader or driver of a rec.

I think ratings don't store date entered so can't do ratings but that's not a big deal.

Recent comments would be perhaps a little bit useful. 

Pretty low priority however.

**Comment by sunehs** [comment]
imo home page is a bit too prominent (maybe an option if we make it customizable at some point), but maybe as tab on /replays

**Comment by j-masci** [comment]
Ya that would make sense actually, new tab on replays page.

**Comment by metsavir** [comment]
How about notification icon with badge to navbar.
<img width="764" alt="Screenshot 2021-04-15 at 0 12 58" src="https://user-images.githubusercontent.com/5804674/114779944-6375bd00-9d7f-11eb-9d7b-4f7363b96222.png">

Click -> Dropdown opens -> Click notification -> Replay

And maybe when dropdown opens, we update `notificationsSeenAt` value for kuski. And badge number is amount of comments newer than that value.

**Comment by j-masci** [comment]
Implemented.
