### ISSUE TITLE
Embed react-recplayer into the project for more control over it

### ISSUE THREAD

**Issue by PabloCorso** [elmadev/elmaonline-site#429]
The idea would be to move in the [react-recplayer](https://github.com/elmadev/recplayer-react) component that is currently a npm package dependency. In this way we could have more control over the inner guts of the player to make it easier to implement other issues like [Can't zoom rec/map viewer on mobile.](https://github.com/elmadev/elmaonline-site/issues/387)

I currently have a [fork repo of the react-recplayer](https://github.com/PabloCorso/recplayer-react), where I did a small rewrite of the component with React hooks and TypeScript. This was really nice to be able to play a bit with the component and quickly test my changes (can test it yourself, download the repo, `npm install` and `npm run dev`).

Anyway, moving the component into the project could be nice, since the whole process could be very slow in the current way:
1. Make changes into the react-recplayer repo (the original or fork).
2. Upgrade the react-recplayer dependecy (or re-install the fork).
3. Re run the project...

It really takes a lot of time for elmaonline-site to go through this for each small change. But it's still really nice to be able to test this component in isolation in a separate repository... Maybe the storybooks can help doing this inside elmaonline-web?

We would still have a dependency to [elmadev/recplayer](https://github.com/elmadev/recplayer), an ES6 port of [recplay](https://github.com/Maxdamantus/recplay). The latter is now rewritten in TypeScript and it's easy to see the interface of it. There are slight differences in this interface definition with the former, which I tried extracting in my fork repo [here](https://github.com/PabloCorso/recplayer-react/blob/master/src/types.tsx).

Btw we could still hack our way in into the inner parts of the current react-recplayer dependency using a reference to it. This is what I tried with the current code:
```jsx
const ref = useRef(null);
if (ref && ref.current) {
  const recPlayer = ref.current;
  // recPlayer references to the RecPlayer class component instance.
 // can access it's functions and state...
}
<RecPlayer ref={ref} />
```

**Comment by ville-j** [comment]
It's a separate package for the reason that it can be easily used in different projects. I don't really understand why it should be moved under bigger repo. If you want to develop and test it you can use npm link to use the dev version in elmaonline repo.

**Comment by PabloCorso** [comment]
I'm not the first to think about this. I do like it being a separate package, although it would be nice to make it more usable for elmaonline-web needs, what other projects use it?

In practice, it is right now a very small react component to wrap elmadev/recplayer, and is not very extensible (ex. open close principle). Currently there are 2 more components inside elmaonline-web to add stuff to it.

RecView -> RecPlayer -npm> ReactRecplayer -> elmadev/recplayer

We could try to simplify this.

I would suggest moving it into a real project like elmaonline-web where we can actively modify it. It is something that elmaonline-web devs can do, make a react component and use elmadev/recplayer directly.

Otherwise we can keep it in a separate package, but I would like to know how to work with that. I did a PR of basically one line 8 days ago and got no response. I believe skint told me he might look at it but I don't know if he did. It seemed to me like a very slow paced project for just one React component, one file. If this grows larger and many projects use it, it could make sense to make a separate package, but for a single file? 

It's about making things more practical. Anyway, if no one thinks this could be good idea I can still propose PRs for the react-recplayer repo, but would like to know other's thoughts.

**Comment by ville-j** [comment]
Well I have several projects and test apps that use it. So far no one else has contributed code to that repo so there aren't any ready thought processes, but I think everyone in the elmadev group should have rights to merge and publish new versions if it continues to be in own repo which I think is convenient for reusability. But the code is quite old and could be updated and rewritten with hooks etc, could make a new version branch from your fork or something... but I would keep it in a separate repo for sure.

**Comment by sunehs** [comment]
We've discussed a number of improvements to recplayer in discord and how best to implement it. One suggestion was this way, to remove one layer of dependency, and implement the specific features desired on eol site. But on the other hand that just creates more division of code, so maybe best to keep it isolated and add more generalised features to it.

I tested developing on recplayer-react using yarn link and that works seemlessly. I can create some issues on that repo for the features we've discussed.

**Comment by PabloCorso** [comment]
Ok that settles that for me. Keep it in its own package for reusable and use yarn link for development in elmaonline-web. Ty for responses.

I must update my fork which still has a few details midway. But if you want to consider it would be cool, besides the hooks which are not really necessary, typescript would be cool as a package. But I'm not sure I correctly set it up so it exports a d.ts file as a package :S

**Comment by ville-j** [comment]
If you want permissions to publish the npm package give me your npm username and I can add you to the maintainers of the package.

**Comment by sunehs** [comment]
sure, that would be nice, same as here: sunehs

**Comment by PabloCorso** [comment]
Ok ty my npm username: pablocorso
