### ISSUE TITLE
Crippled top times (level page)

### ISSUE THREAD

**Issue by j-masci** [elmadev/elmaonline-site#462]
No turn / No volt / No throttle top times lists added to level page. Thoughts? Seems easy to implement. Doubt people would use it much. Would be retroactive for all previous times. Can just read from all finished table.

**Comment by sunehs** [comment]
I think it's quite wanted. In the past I had some script to pick out the relevant times and put into crippled table, but yea I think we can just filter them from allfinished directly.

**Comment by j-masci** [comment]
Doing some testing on the dev server, **SELECT * FROM allfinished WHERE LevelIndex = 2 AND Turn = 0** was taking over 20 seconds to complete the first time running it in a while. That means it's could be more difficult to implement than previously thought. Perhaps for internals only we could find some way to do caching but not for other levels. Although actually, counting the number of finishes seems fast regardless of the number returned, so could cache conditionally based on that. But once you add all the crippled conditions in there we might still be looking at 30-60 seconds to build the cache initially which is kind of a bit problematic IMO. So.. not sure what the best approach would be here.

**Comment by j-masci** [comment]
I ran this again and now completing pretty fast.. like 1-2 seconds for levels with the most finishes. This is about what I would have expected. No idea why it was consistently 20 seconds before. Maybe i'll work on the feature afterall.

**Comment by j-masci** [comment]
Implemented. 

However would like to maybe add maxSpeed as well. A bit more work than the others as the re usable pieces of code only understand time right now.

**Comment by j-masci** [comment]
Done.
