### ISSUE TITLE
Levelpack page personal tab should show difference from current record

### ISSUE THREAD

**Issue by j-masci** [elmadev/elmaonline-site#480]
There's already a difference column that is active if the person has any multi times, then it shows difference between your personal best, and multi-best. But does not show difference between your personal best and best for all players. Seems like it would be useful. Also, the data seems to already be there. Likely very quick to implement.

**Comment by sunehs** [comment]
Yes agree, would also like other compare options, such as to other kuskis, to team/nation records (and target times, old wr tables for ints)
