### ISSUE TITLE
Elma.online favicon is react native icon

### ISSUE THREAD

**Issue by j-masci** [elmadev/elmaonline-site#484]
At least on my phone anyways.

**Comment by j-masci** [comment]
not on desktop though so nvm. maybe not favicon but some icon is shown for react native when looking at multiple chrome tabs on phone.

**Comment by sunehs** [comment]
https://github.com/elmadev/elmaonline-web/tree/dev/public there's logo192 and logo512 here which is the react logo, should be updated but I don't have the elma head in that big res
