### ISSUE TITLE
Player profile page

### ISSUE THREAD

**Issue by ville-j** [elmadev/elmaonline-site#53]
Reference: [http://elmaonline.net/players/adi](http://elmaonline.net/players/adi)

- Name
- Team
- Nationality
- Recently played battles
- Battle wins count

Other ideas: #19

**Comment by pawq** [comment]
It could be quite useful if the "Recent battles" list was not limited to 20 or whatever, but be scrollable with multiple pages. If that was to be implemented, then a "jump to date" feature would be essential imo.

Also, the list of player rights (and achievements?) should be there imo.

**Comment by ville-j** [comment]
I just happened to make the list "browsable" yesterday, but it's not possible to jump to certain page or date directly (yet) because of reasons so you have to browse to the older ones page by page.
