### ISSUE TITLE
New replay filter - Internal

### ISSUE THREAD

**Issue by culinko** [elmadev/elmaonline-site#541]
Hi again :)

As an internal levels enthusiast, I'd like to request a new addition to our existing replay filters (TAS, bug, DNF, etc.) which would show only replays for internal levels. The filter could be called just simply "Internal" or whatever else would make sense.

Thanks :)

**Comment by metsavir** [comment]
We already have this. Check https://elma.online/levels/packs/Int/replays

**Comment by culinko** [comment]
Thanks a lot for the link, I missed this specific location of replays for internal levels. However, as far I can see, it's not possible to combine this selection with other filters, so you wouldn't be able to search for e.g. Internal + SL replays.

Do you think filter could be added to the page https://elma.online/replays here?

![image](https://user-images.githubusercontent.com/11700272/156435778-a8bee0b6-5e3d-45e8-ad6a-f65827f99f23.png)

Thanks!

**Comment by metsavir** [comment]
<img width="1271" alt="Screenshot 2022-03-02 at 21 35 48" src="https://user-images.githubusercontent.com/5804674/156436318-ed41ce2c-6475-43a4-91b9-b916e337d286.png">

**Comment by culinko** [comment]
Hmm, ignore my previous reply then, guess I'm just too tired atm. Thanks for pointing it out :)
