### ISSUE TITLE
Level page

### ISSUE THREAD

**Issue by ville-j** [elmadev/elmaonline-site#55]
Reference: [http://elmaonline.net/statistics/level/416713](http://elmaonline.net/statistics/level/416713).

Separate page for viewing a single level.

- Level map (use recplayer?)
- Level information
- Every player's best time in the level
- Comments ?
- All replays driven in the level ?

**Comment by pawq** [comment]
All replays driven in the level would be A, MA, ZING. Definitely not a useless feature.
