### ISSUE TITLE
Prevent screen sleep on mobile for long recs

### ISSUE THREAD

**Issue by PabloCorso** [elmadev/elmaonline-site#558]
It would be nice if screen doesn't go to sleep while watching long recs. Like if it were a video playing, so don't have to constantly regain focus on the screen while watching it.

I don't know if this is doable outside recplayer. The solution could be to play a video or audio on the background, or using a new Lock API.

**Comment by sunehs** [comment]
Should be easy enough to implement wake lock, not supported in firefox yet but watching long recs has the memory leak issue in firefox anyway, so no point implementing some video playback hack.

For reference: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API

**Comment by sunehs** [comment]
https://github.com/elmadev/elmaonline-web/commit/f8116e3afc042d521a8752b3b04139b7fc9cf3ef
