### ISSUE TITLE
Unable to start the server

### ISSUE THREAD

**Issue by ville-j** [elmadev/elmaonline-site#563]
After cloning the repo and running yarn install I am unable to start the server with `yarn start`

```
PS C:\Users\v_jan\Documents\code\elmaonline-site> yarn start
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --es-module-specifier-resolution=node --no-warnings src/index.js`
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\v_jan\Documents\code\elmaonline-site\src\config' imported from C:\Users\v_jan\Documents\code\elmaonline-site\src\index.js
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:257:11)
    at moduleResolve (node:internal/modules/esm/resolve:850:10)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:829:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:412:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v19.0.0
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by j-masci** [comment]
Is there a config file to copy or something? Not at pc atm.

**Comment by sunehs** [comment]
config is there by default, sounds more like issue with esm mode. Ismo ran into similar and had to update node, should be at least 16.17 but looks like you have 19. Make sure you run `corepack enable` and then `yarn` after that.

**Comment by ville-j** [comment]
Yeah I realized I didn't have corepack installed because I use node through nvm.  So I had to manually install it but I don't know what's wrong with npm nowadays since it didn't work either so I had to downgrade to node 16.10.0 with npm 7.24.0 and then I could install corepack manually. So now everything should be right but I get this error now
```
PS C:\Users\v_jan\Documents\code\elmaonline-site> yarn start
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --es-module-specifier-resolution=node --no-warnings src/index.js`
file:///C:/Users/v_jan/Documents/code/elmaonline-site/src/utils/dataImports.js:19
import * as kuskiMapData from '../data/json/kuskimap.json' assert {type: "json"};
                                                           ^^^^^^

SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (node:internal/modules/esm/translators:146:18)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by ville-j** [comment]
Alright I got it working now. It appears you need to use node v16.15.0 or later for this project. But my problem was also that since I'm using node through nvm I had to manually install corepack and there was some kind of npm problem when I tried to install it. However it fixed by updating nvm and first uninstalling all node versions through nvm and then reinstalling the one that I want (16.18.0 LTS). After that I could also install corepack and enable it and start the server. Just writing this here in case of someone else having these same kind of problems.. maybe I also update the readme file.
