### ISSUE TITLE
Swapped labels of Dead % and Esced % in Play Stats on Level Page

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#566]
As in the title, it seems that the Dead % and Esced % columns in Play Stats on the Level Page have their labels swapped. Noticed here:
https://elma.online/levels/543574
It says that 88.3% of the playtime was esced, which in a long pipe is hnnng :) Total playtime is 8h and I have 3h40 of Dead runs, so it's defo wrong. Also from these stats the average length of a Dead run is ~6sec, and for an Esced run it's ~18sec. I have 3sec and 20sec for Esced and Dead respectively (which makes perfect sense), so I think the column names in Play Stats are just swapped.

**Comment by j-masci** [comment]
Are you suggesting that int 01 doesn't have an 85.4% death rate? :D

**Comment by sunehs** [comment]
Checking that level in database I get this:
![billede](https://user-images.githubusercontent.com/11961836/198699895-0274737e-32dc-477f-a263-07cba5a84430.png)
and double checking in time table:
![billede](https://user-images.githubusercontent.com/11961836/198699970-bb3e8ac2-e1ed-46af-af54-e9a5d5e9c084.png)
so something does seem wrong

**Comment by j-masci** [comment]
You'd have to compare with the unadjustedTime* cols, since those do not filter out runs that appear to be afk or reefer like behavior

**Comment by j-masci** [comment]
Cols here seem to be in the wrong order. Maybe there's still time for someone to haktober this one https://github.com/elmadev/elmaonline-web/blob/dev/src/pages/level/LevelInfoLevelStats.js
