### ISSUE TITLE
Battle league events don't show the year

### ISSUE THREAD

**Issue by metsavir** [elmadev/elmaonline-site#633]
<img width="634" alt="Näyttökuva 2023-11-23 kello 18 11 18" src="https://github.com/elmadev/elmaonline-site/assets/5804674/d76ca7b8-bda2-46f2-b460-e90998a96f64">

**Comment by sunehs** [comment]
https://github.com/elmadev/elmaonline-web/commit/6a9672d4a31cbac46d2de9f20c2518ea0a61050f
