### ISSUE TITLE
Show `DNF` and `TAS` info somehow in "Replays in level" list

### ISSUE THREAD

**Issue by metsavir** [elmadev/elmaonline-site#646]
<img width="926" alt="Näyttökuva 2024-1-30 kello 18 50 38" src="https://github.com/elmadev/elmaonline-site/assets/5804674/0247c016-4996-46ca-99f4-700c5c659219">

**Comment by sunehs** [comment]
would prefer some icons for tas and dnf (of course would be nice if dnf worked correctly always as well), also "excluded tags" would be nice, maybe second click will make it red and excluded and/or ctrl+click
