### ISSUE TITLE
Levelpack admin page crash

### ISSUE THREAD

**Issue by makitalo** [elmadev/elmaonline-site#653]
Undefined things here https://github.com/elmadev/elmaonline-web/blob/1392d72f9802e20557c004258ce16ff71b34431e/src/pages/levelpack/Admin.jsx#L76

Easiest to trigger by first updating pack details and then using Search Levels, or vice versa.

**Comment by sunehs** [comment]
https://github.com/elmadev/elmaonline-web/commit/75f59fd5c363396f97f38fc6bee1cb295796236d
