### ISSUE TITLE
intXX level search blocks other levels starting with int

### ISSUE THREAD

**Issue by makitalo** [elmadev/elmaonline-site#672]
The qwquu -> int search feature prevents other levels starting with int, like `Intilt01` (https://elma.online/levels/19845) or `INT009` (https://elma.online/levels/278740), from showing up in search results.

For example `Intilt01` shows up when searching with `in` or `intilt0`, but not when searching with `int`, `inti`, `intil`, or `intilt`.
And searching with `int009` returns internal 09 as expected, but the INT009 level doesn't show up.

**Comment by sunehs** [comment]
https://github.com/elmadev/elmaonline-site/commit/57d8eabb54d92d3a92444e77934184617e9024b4
