### ISSUE TITLE
Integration of a file upload page

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#70]
Reference: http://kopasite.net/up

The upload page on Kopasite is great, and has been for years. But, having said that, I'm very much for a shift to a centralised modern Elma site, and I think it would be great to have a file upload system there. Could literally be a copycat of the current Kopasite one, with a neat elmaonline.net/up URL.

Not a very high priority though I suppose.

**Comment by sunehs** [comment]
My plan is to be able to sunset kopasite at some point, once important features has been replicated elsewhere. So yes agree.
