### ISSUE TITLE
Comparing to next target gets confused when you are exactly on the target

### ISSUE THREAD

**Issue by metsavir** [elmadev/elmaonline-site#709]
<img width="643" alt="Näyttökuva 2024-10-06 kello 21 27 15" src="https://github.com/user-attachments/assets/73c0ecbd-06e1-47e6-94b0-d077edf7e703">

**Comment by jgouly** [comment]
Looking into this a bit: https://github.com/elmadev/elmaonline-web/blob/dev/src/components/Time.jsx#L54 
```
    if (time === 0) {
      return `${apples} apple${apples !== 1 ? `s` : ``}`;
    }
```

I'm not sure when `time === 0` is true other than this case. Apple battles seem to have specific handling.

Also these cases should(?) change to >= from >. https://github.com/elmadev/elmaonline-web/blob/dev/src/components/Compare.jsx#L32

**Comment by sunehs** [comment]
https://github.com/elmadev/elmaonline-web/pull/260/commits/e0ea47795ebe0c41842056d09ebf37a4323acd59
