### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#78]
Obvious feature :)

+ [x] A search function for levels
  - [x] Ability to search by filename
  - [x] In separate columns display: filename; level name; level index
  - [x] Show levelpacks in search results
- [x] A search function for battles
  - [x] Ability to search by filename and designer
  - [x] In separate columns display: filename; battle index; level index; started date; designer
* [ ] A search function for replays
  - [x] Ability to search by filename
  - [x] Search by level filename, driven by, possibly also uploaded by
  - [x] In separate columns display: replay filename, level filename, driven by
  - [x] show uploaded date, uploaded by
+ [x] A search function for players
* [x] A search function for teams
- [x] Wildcard support
- [x] Search URL support (so that clicking Enter in search box pushes history and goes to a new url, so that can go back to search results if need be)

**Comment by sunehs** [comment]
Moved some features to https://github.com/elmadev/elmaonline-site/issues/216 so I can close this for the milestone.
