### ISSUE TITLE
Mixed time zones in Duration of ongoing battle

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#85]
The times in the left-most column of the Latest Battles table seem to be in CKT (Central Kopaka Time, GMT+1), but it seems like the Duration column takes UTC (?) time to calculate elapsed time of ongoing battle.

Example:
40-minute battle started at 2:05 Kopaka time
Elapsed time is equal to current time - battle start time
UTC time is 1:24
Elapsed time = 1:23-2:05 = -41min
-41/20 displayed in the Duration column for ongoing battle

![bugreport](https://user-images.githubusercontent.com/19539089/55765159-59b97080-5a66-11e9-999c-33041761da81.png)

The Duration field should use the same time zone for both `current time` and `battle started time`.

**Comment by ville-j** [comment]
The whole StartedUtc (which is used at least in said list) is obsolete, incorrect and erroneous. All times on the site should use the normal datetime column in the db and display through LocalTime component which can be configured to use whatever fixed timezone if that's desired.

**Comment by sunehs** [comment]
https://github.com/elmadev/elmaonline-site/commit/9bebde010283b79d39865f8269eb6c1aa6c76f8f
