### ISSUE TITLE
Incorrect data displayed in battle card

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#89]
- [x] Currently the battle card component displays data for the most recent battle with the "Queued" status. It should display data for the most recent battle overall. Currently, because aborted battles show up as "Queued", the battle card component displays data for the most recent aborted battle, if no battle is in queue.

- [x] Also, while it displays the correct (live) filename, Author, Type, Duration and map, it displays 
an incorrect "Started" time. The same "Started" time was also displayed on the test database (https://test.elma.online/), but does not correspond to the "Started" time of the most recent battle there. I assume it was some temporary placeholder.

- [x] Furthermore, the battle card component displays a broken image symbol for Queued levels where the level is not yet available for download (pic 1), and it _does_ display the map if the level is available for download (for example when the designer unlocked it before it started) (pic 2). It should display no map for Queued battles, regardless of the upload status.

- [x] Battle ID is displayed immediately after levname (pic below)

![bog](https://user-images.githubusercontent.com/19539089/55839769-ff311a80-5b20-11e9-8038-d16bc12d1ab4.png)

**Comment by sunehs** [comment]
https://github.com/elmadev/elmaonline-site/commit/d3c891e8b5f1351e9f75c36c459c335d81df9cb1

**Comment by sunehs** [comment]
https://github.com/elmadev/elmaonline-site/commit/9bebde010283b79d39865f8269eb6c1aa6c76f8f
