### ISSUE TITLE
Find a way for people to easily install MySQL locally

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#9]
What's the best way to install MySQL locally, so it's easy for people to install the project.

**Comment by hexjelly** [comment]
Don't think there's any universal quick solution to this, but luckily pretty easy and it has good support for all OSs anyway. Any Linux distro will 100% have it in their package manager. On Windows it has a pretty simple installer available, or you can use the Chocolatey windows package manager thing. Maybe just linking here is enough? [https://dev.mysql.com/downloads/mysql/](https://dev.mysql.com/downloads/mysql/)

**Comment by sunehs** [comment]
I just have it from the wamp installation I use for PHP stuff, pretty small and quick to install.
