### ISSUE TITLE
Double back click needed to go back from some pages

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#92]
Many replay pages require the <kbd>back</kbd> key to be pressed twice to go back to the previous page. The first <kbd>back</kbd> click brings back the previous browser tab title and scroll status (how far the page was scrolled in the previous state), and the second click actually goes back to the previous content.

I thought it happened only for some pages, but actually it's intermittent. Opening the same battle or replay page many times, sometimes it'll require 2 clicks to go back, and sometimes 1. I couldn't figure out what it depends on.

```
[07:27] bene: @pawq weird behavior on 2nd back click is because there are double history.push at least for rec because RecList and RecListItem both do it.
Or something like that I looked at it for a few minutes yesterday.
(...)
[11:05] bene: I literally did this:
Wow double back why
Wow duplicate function in components
Wow both push history```

**Comment by sunehs** [comment]
was fixed a while ago, if it appears again somewhere the reason was that both the table row and the replay filename was a link and so it linked twice if you clicked on filename
