### ISSUE TITLE
Mobile layout issues

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#95]
- By default the site opens with the sidebar open, which takes up like 80% of the width of the screen. The sidebar also doesn't close when an item is clicked, need to close it manually. I think below a certain window width threshold the site should load with the sidebar hidden, and the sidebar should hide automatically when an item is selected. (gif 1)

- Kuskis page and individual kuski pages work fine (main pages are responsive, tables shrink up to a certain degree and then become side-scrollable). But those tables simply go edge to edge, also in large mode, which is probably not the goal. (gif 2)

- The "Latest Battles" and "Latest Replays" tables on the homepage do not respond correctly. The tables shrink with the window width (and swap to one-below-the-other below a certain width threshold), but the table contents don't, so they overlap, and extend beyond the tables. (gif 3)

- The Battles page is similar to the Kuskis page (edge-to-edge table, responds correctly). Individual battle pages have the same table types as the homepage, but they don't have issues (probably because there are few enough columns that the contents don't go out of table).

- The individual level pages also respond correctly.

![mobile1](https://user-images.githubusercontent.com/19539089/55813034-fff78b80-5ae3-11e9-9ba8-b9f05d6d7a68.gif)
![mobile2](https://user-images.githubusercontent.com/19539089/55813035-fff78b80-5ae3-11e9-8281-24d4ffc944db.gif)
![mobile3](https://user-images.githubusercontent.com/19539089/55813036-00902200-5ae4-11e9-8c26-c7522def3606.gif)

**Comment by ville-j** [comment]
> Kuskis page and individual kuski pages work fine (main pages are responsive, tables shrink up to a certain degree and then become side-scrollable). But those tables simply go edge to edge, also in large mode, which is probably not the goal. (gif 2)

This (edge to edge rows) is intended behavior, also in battles page. Maybe on smaller screens some columns of the tables could be hidden, but I think that's quite small detail and horizontal scrolling works quite ok with these tables instead of making some information unavailable.

**Comment by pawq** [comment]
What if we want to add more elements/components (such as filters) to those pages though? Won't there have to be limited-width tables then, like on the Homepage?

**Comment by ville-j** [comment]
Sure that can be done when there's actually something to put in there.

**Comment by j-masci** [comment]
I think this has pretty much been taken care of.
